//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfiXML_Map_Reader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cfiXML_Map_Reader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionPersonCreated_TransactionPersonModified;Page1;AB;64
        ///TransactionPersonChecked;Page1;AD;64
        ///OwnerName;Page1;Q;14
        ///ProjectID;Page1;Q;18
        ///ProjectName;Page1;Q;16
        ///PurchaseOrderID;Page1;Q;28
        ///TransactionRemark;Page1;K;64
        ///RequistionID;Page1;Q;26
        ///RevisionID;Page1;B;64
        ///PumpSerialNumber;Page1;Q;24
        ///PumpSerialNumber;Page2;AH;8
        ///SiteName;Page2;F;6
        ///SpecID;Page1;Y;26
        ///TransactionDateTime;Page1;E;64
        ///DataSheetType;Page2;H;4
        ///InstrumentationISOAPIDataSheetID;Page4;R;5
        ///PumpDesignStandard;Page2;Y;4
        ///PumpStan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Map_XLS_API610 {
            get {
                return ResourceManager.GetString("Map_XLS_API610", resourceCulture);
            }
        }
    }
}
